Form/Type/MaskedInputType.php
<?php

namespace Nitra\StoreBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormView;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class MaskedInputType extends AbstractType
{
    /**
     * @inheritdoc
     */
    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        parent::buildView($view, $form, $options);
        $view->vars['parameters']   = $options['parameters'];
        $view->vars['definitions']  = $options['definitions'];
        $view->vars['mask']         = $options['mask'];
    }

    /**
     * @inheritdoc
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        parent::setDefaultOptions($resolver);
        $resolver->setDefaults(array(
            'parameters'    => array(),
            'definitions'   => array(
                '9'             => "[0-9]",
                'a'             => "[A-Za-z]",
                '*'             => "[A-Za-z0-9]",
            ),
        ))->setRequired(array('mask'));
    }

    /**
     * @inheritdoc
     */
    public function getParent()
    {
        return 'text';
    }

    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'masked_input';
    }
}

Resources/views/EmailTemplates/sendOrderMailBuyer.html.twig
{% trans_default_domain "NitraStoreBundle" %}
<table width="660" cellspacing="0" cellpadding="0" align="center" style="color: #555; background-color: #fff; font-size: 12px; font-family: Arial, sans-serif; line-height: 1.2;">
    <tbody>
        <tr>
            <td>
                <table width="660" cellspacing="0" cellpadding="0" align="center" style="font-family: Arial, sans-serif; font-size: 12px;">
                    <tbody>
                        {% block email_header %}
                            <tr style="background-color: #f6f6f6;">
                                <td width="250" colspan="2">
                                    <div class="logo" style="margin-left: 20px;">
                                        {% block logo %}
                                            {{ orderData.store_name }}
                                        {% endblock logo %}
                                    </div>
                                </td>
                                <td width="207">
                                    <div class="phones">
                                        {% block email_contacts %}
                                            {% render controller("NitraStoreBundle:Common/Common:contacts") %}
                                        {% endblock email_contacts %}
                                    </div>
                                </td>
                                <td width="145">
                                    <div class="day">
                                        {% block email_work_time %}
                                            {% render controller("NitraTextBlockBundle:TextBlock/TextBlock:TextBlock", {'location':'work_time_footer'}) %}
                                        {% endblock email_work_time %}
                                    </div>
                                </td>
                            </tr>
                        {% endblock email_header %}
                        {% block email_name_buyer %}
                            <tr>
                                <td colspan="4">
                                    <div style="margin:7px 20px 10px 20px; font-size:14px;">{% block buyer_name %}{{ 'order.mailingThemes.hello'|trans }} {{ orderData.fio }}!{% endblock buyer_name %}</div>
                                </td>
                            </tr>
                        {% endblock email_name_buyer %}
                        {% block email_content %}
                            <tr>
                                <td colspan="4">
                                    <div style="font-size: 18px; margin: 5px 20px 15px;">
                                        <span style="color: #2C94CC;">{{ 'order.mailingThemes.success'|trans }}</span>
                                        <span style="color: #544541;">{{ 'order.mailingThemes.text'|trans }}</span>
                                    </div>
                                </td>
                            </tr>
                            {% if orderId %}
                                <tr>
                                    <td colspan="4">
                                        <div style="font-size: 14px; margin: 10px 20px;">{{ 'order.mailingThemes.orderNumber'|trans }} <strong>{{ orderId }}</strong></div>
                                        <div style="border-bottom: 1px solid #bab4b3; margin: 0 20px; line-height: 0;"> &nbsp;</div>
                                    </td>
                                </tr>
                            {% endif %}
                            {% set amount = 0%}
                            {% for product in orderData.products %}
                                <tr>
                                    <td colspan="4">
                                        <table width="620" align="center" cellspacing="0" cellpadding="0" style=" border-bottom: 1px solid #bab4b3; font-family: Arial, sans-serif;">
                                            <tbody>
                                                <tr>
                                                    <td width="140">
                                                        <div style="margin: 10px 20px;">
                                                            <a href="{{ url('product_page', {'slug': product.alias}) }}">
                                                                <img src="{{ product.image|default('images/no_image.jpg')|imagine_filter('email_product_image') }}" title="{{ product.fullName }}" alt="{{ product.fullName }}" border="0" />
                                                            </a>
                                                        </div>
                                                    </td>
                                                    <td colspan="3">
                                                        <div style="font-size: 16px; margin: 10px 0;">
                                                            <a href="{{ url('product_page', {'slug': product.alias}) }}" style="color:#555;">{{ product.fullName }}</a>
                                                        </div>
                                                        <div style="margin-bottom: 15px;">
                                                            <table width="414" cellspacing="0" cellpadding="5" border="1" style="border-color:#bab4b3; border-collapse: collapse; font-family: Arial, sans-serif; font-size: 12px;">
                                                                <tbody>
                                                                    <tr>
                                                                        <th style="font-size: 14px; border-color:#bab4b3;">{{ 'order.mailingThemes.price'|trans }}</th>
                                                                        <th style="font-size: 14px; border-color:#bab4b3;">{{ 'order.mailingThemes.count'|trans }}</th>
                                                                        <th style="font-size: 14px; border-color:#bab4b3;">{{ 'order.mailingThemes.sale'|trans }}</th>
                                                                        <th style="font-size: 14px; border-color:#bab4b3;">{{ 'order.mailingThemes.total'|trans }}</th>
                                                                    </tr>
                                                                    <tr>
                                                                        <td align="center" style="color:#2C94CC; font-size: 18px; border-color:#bab4b3;">{{ product.price|price }}</td>
                                                                        <td align="center" style="color:#2C94CC; font-size: 18px; border-color:#bab4b3;">{{ product.quantity }}</td>
                                                                        <td align="center" style="color:#2C94CC; font-size: 18px; border-color:#bab4b3;">{{ product.discount }}</td>
                                                                        <td align="center" style="color:#2C94CC; font-size: 18px; border-color:#bab4b3;">{{ (product.priceDiscount * product.quantity)|price }}</td>
                                                                        {% set amount = amount + product.priceDiscount * product.quantity %}
                                                                    </tr>
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                    </td>
                                                <tr>
                                            </tbody>
                                        </table>
                                    </td>
                                </tr>
                            {% endfor %}
                            <tr>
                                <td colspan="4" align="right">
                                    <div style="font-size: 20px;  margin: 5px 20px;">{{ 'order.mailingThemes.total'|trans }}: <span style="color:#2C94CC; font-size: 24px;">{{ amount|price }}</span></div>
                                </td>
                            </tr>
                        {% endblock email_content %}
                        {% block email_footer %}
                            <tr>
                                <td colspan="4">
                                    <div  style="margin: 30px 20px 10px;">
                                        <p style="margin: 0px; color: #717171; font-style: italic;">{{ 'order.mailingThemes.team'|trans }} <a href="{{ url('nitra_store_home_index') }}">{{ orderData.store_name }}</a><p>
                                        <p style="margin: 0px; color: #717171; font-style: italic;">{{ 'order.mailingThemes.letter'|trans }}</p>
                                    </div>
                                </td>
                            </tr>
                        {% endblock email_footer %}
                    </tbody>
                </table>
            </td>
        </tr>
    </tbody>
</table>

Resources/views/EmailTemplates/sendOrderMailManager.html.twig
{% trans_default_domain "NitraStoreBundle" %}
<table width="600" cellspacing="0" cellpadding="0" align="center" style="color: #555;  font-size: 12px; font-family: Arial, sans-serif; line-height: 1.2;">
    <tbody>
        <tr>
            <td>
                <table cellspacing="0" cellpadding="0" align="center">
                    <tr>
                        <td collspan="4" style="border: 1px solid #dadada; background-color: #f6f6f6; box-shadow: 1px 1px 0px #fff inset, -1px -1px 0px #fff inset;">
                            <table width="660" cellspacing="0" cellpadding="0" align="center" style="font-family: Arial, sans-serif; font-size: 14px;">
                                <tbody>
                                    {% block table_content %}
                                        <tr>
                                            <td colspan="4">
                                                <div style="margin: 10px 20px 30px">
                                                    <div style="font-size: 20px; text-align: center; margin-bottom: 30px;">
                                                        {{ 'order.mailingThemes.orderSite'|trans|raw }} {{ orderData.store_name }} {% if orderId %}<span style="color: #2C94CC;">№{{ orderId|raw }}</span> {{ 'order.mailingThemes.create'|trans|raw }}{% else %}{{ 'order.mailingThemes.noCreate'|trans|raw }}{% endif %}
                                                    </div>
                                                    <div style="font-size: 16px; color: #2C94CC; margin-bottom: 6px;">{{ 'order.mailingThemes.name'|trans }} <span style="font-size: 16px; color: #555;">{{ orderData.fio }}</span></div>
                                                    <div style="font-size: 16px; color: #2C94CC; margin-bottom: 6px;">{{ 'order.mailingThemes.phone'|trans }} <span style="font-size: 16px; color: #555;">{{ orderData.phone }}</span></div>
                                                    {% if orderData.email is defined and orderData.email %}
                                                        <div style="font-size: 16px; color: #2C94CC; margin-bottom: 6px;">{{ 'order.mailingThemes.email'|trans }} <span style="font-size: 16px; color: #555;">{{ orderData.email }}</span></div>
                                                    {% endif %}
                                                        <div style="font-size: 16px; color: #2C94CC; margin-bottom: 6px;">{{ 'order.mailingThemes.city'|trans }} <span style="font-size: 16px; color: #555;">{{ orderData.city_name }}</span></div>
                                                    {%if orderData.comment is defined and orderData.comment %}
                                                        <div style="font-size: 16px; color: #2C94CC; margin-bottom: 6px;">{{ 'order.mailingThemes.info'|trans }} <span style="font-size: 16px; color: #555;">{{ orderData.comment|raw }}</span></div>
                                                    {% endif %}
                                                </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td colspan="4" style="padding: 0 20px;">
                                                <table width="560" cellspacing="0" cellpadding="10" align="center" border="1" style="border-color: #bab4b3; border-collapse: collapse; font-family: Arial, sans-serif; font-size: 12px;">
                                                    <tbody>
                                                        <tr>
                                                            <th style="font-size: 14px; border-color:#bab4b3;">{{ 'order.mailingThemes.product'|trans }}</th>
                                                            <th style="font-size: 14px; border-color:#bab4b3;">{{ 'order.mailingThemes.brand'|trans }}</th>
                                                            <th style="font-size: 14px; border-color:#bab4b3;">{{ 'order.mailingThemes.category'|trans }}</th>
                                                            <th style="font-size: 14px; border-color:#bab4b3;">{{ 'order.mailingThemes.count'|trans }}</th>
                                                            <th style="font-size: 14px; border-color:#bab4b3;">{{ 'order.mailingThemes.price'|trans }}</th>
                                                            <th style="font-size: 14px; border-color:#bab4b3;">{{ 'order.mailingThemes.sale'|trans }}</th>
                                                            <th style="font-size: 14px; border-color:#bab4b3;">{{ 'order.mailingThemes.total'|trans }}</th>
                                                        </tr>
                                                        {% set amount = 0%}
                                                        {% for product in orderData.products %}
                                                            <tr>
                                                                <td>{{ product.name }}</td>
                                                                <td>{{ product.brand }}</td>
                                                                <td>{{ product.category }}</td>
                                                                <td>{{ product.quantity }}</td>
                                                                <td>{{ product.price|price }}</td>
                                                                <td>{{ product.discount }}</td>
                                                                <td>{{ product.priceDiscount * product.quantity|price }}</td>
                                                                {% set amount = amount + product.priceDiscount * product.quantity %}
                                                            </tr>
                                                        {% endfor %}
                                                    </tbody>
                                                </table>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td colspan="4" align="right">
                                                <div style="font-size: 20px;  margin: 20px;">{{ 'order.mailingThemes.total'|trans }}: <span style="color: #2C94CC; font-size: 24px;">{{ amount|price }}</span></div>
                                            </td>
                                        </tr>
                                    {% endblock table_content %}
                                </tbody>
                            </table>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
</table>